name: ISSNow
options:
  bundleIdPrefix: com.example
settings:
  base:
    SWIFT_VERSION: 5.0
    ASSETCATALOG_COMPILER_APPICON_NAME: ""
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
packages:
  SatelliteKit:
    url: https://github.com/gavineadie/SatelliteKit.git
    from: 2.1.0
targets:
  ISSNow:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: ISSNow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.issnow
    dependencies:
      - package: SatelliteKit
